test: add reproducer for GCC 14 float limits conflict
Result:

actual-stderr> /CastXML/test/input/GCC14-limits-conflict.cxx:30:15: error: typedef redefinition with different types ('float' vs 'struct __castxml_Float32_s')
actual-stderr> 30 | typedef float _Float32;
actual-stderr> | ^
actual-stderr> <built-in>:63:18: note: expanded from macro '_Float32'
actual-stderr> 63 | #define _Float32 __castxml_Float32
actual-stderr> | ^
actual-stderr> <built-in>:68:107: note: previous definition is here
actual-stderr> 68 | typedef struct __castxml_Float32_s { float x; operator float() const; __castxml_Float32_s(float); } __castxml_Float32;
actual-stderr> | ^
actual-stderr> /CastXML/test/input/GCC14-limits-conflict.cxx:31:16: error: typedef redefinition with different types ('double' vs 'struct __castxml_Float64_s')
actual-stderr> 31 | typedef double _Float64;
actual-stderr> | ^
actual-stderr> <built-in>:65:18: note: expanded from macro '_Float64'
actual-stderr> 65 | #define _Float64 __castxml_Float64
actual-stderr> | ^
actual-stderr> <built-in>:70:110: note: previous definition is here
actual-stderr> 70 | typedef struct __castxml_Float64_s { double x; operator double() const; __castxml_Float64_s(double); } __castxml_Float64;
actual-stderr> | ^
actual-stderr> 2 errors generated.