castxml: Fix `__float128` simulation with `-std=gnu++{11,14}`
Since LLVM/Clang does not natively support the `__float128` GNU
extension CastXML inserts its own preamble declaring the name as a
typedef to a struct that we handle specially during output.  This allows
us to support `--castxml-cc-gnu g++` preprocessor conditions that cause
code to use `__float128`.  However, when Clang has GNU extensions
enabled with C++11 or later it adds its own fake `__float128` builtin
type in order to tolerate the type while parsing.  These two workarounds
conflict, leading to:

    error: typedef redefinition with different types
           ('struct __castxml__float128' vs '__float128')

Fix this by skipping our own typedef for `__float128` when we expect
Clang to provide its own fake builtin type.  Then teach our output code
to recognize the Clang builtin and replace it with FundamentalType just
as we do for or own struct `__castxml__float128`.

GitHub-Issue: 44